name: Run Telegram Bot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # ভার্সন আপডেট করা হয়েছে

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # পাইথন ৩.১১ ব্যবহার করা হয়েছে

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI yt-dlp

      - name: Run Bot
        run: python bot.py
        
